[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "hedgesim"
version = "2026.03"
description = "Simulation tools for hedging research"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Pritam Dalal" }
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]